steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/ml_ops_detect_ai_generated_text/trainer', '-f', 'dockerfile/trainer.dockerfile', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/ml_ops_detect_ai_generated_text/trainer']