seed: 42
model_path: "models/"
data_path: "processed/llm-detect-ai-generated-text"


#
max_epochs: 1
max_steps: 10
use: "epochs"
#use: "steps"
log_every_n_steps: 5
batch_size: 16

learning_rate: 0.001


