seed: 42
model_path: "models/"
model_bucket: ""
data_path: "processed/llm-detect-ai-generated-text"
data_bucket: ""

#
max_epochs: 10
max_steps: 10
use: "epochs"
#use: "steps"
log_every_n_steps: 5
batch_size: 16

learning_rate: 0.001


