# Possible params here: https://docs.wandb.ai/guides/sweeps/define-sweep-configuration

program: ml_ops_detect_ai_generated_text/train_model.py
name: lr_sweep
method: grid

metric:
  name: accuracy
  goal: maximize

parameters:
  training.learning_rate:  # Use - to override values
      values:
        - 0.001
        - 0.01

# pass in the command line arguments inline with hydra
command:
  - ${env}
  - python
  - ${program}
  - ${args_no_hyphens}